Repository submariner-io/cloud-prepare, pull requests merged in 2021-05, with the labels that each got.

#24 Remove ReportingStatus
  pkg/api/api.go
Labels: cloud-prepare

#23 Updated readme with useful info
  .markdownlint.yml
  README.md
Labels: cloud-prepare

#44 Add CII badge, remove PR-triggered badges
  README.md
Labels: cncf, documentation, ready-to-test

#45 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf, documentation, ready-to-test

#46 Update the copyright statements to match CNCF recs
  .github/workflows/linting.yml
  .legal.json
  .licenserc.json
  pkg/api/api.go
  pkg/aws/aws.go
  pkg/aws/ec2helpers.go
  pkg/aws/errors.go
  pkg/aws/gw-machineset.go
  pkg/aws/machinesets.go
  pkg/aws/securitygroups.go
  pkg/aws/subnets.go
  pkg/aws/validations.go
  pkg/aws/vpcs.go
Labels: cncf
