Repository submariner-io/cloud-prepare, pull requests merged in 2022-06, with the labels that each got.

#262 Check if gateway security group in tagged nodes
  pkg/rhos/ocpgwdeployer.go
  pkg/rhos/securitygroups.go
Labels: backport

#303 Automated backport of #262: Check if security groups are associated with the nodes
  pkg/rhos/ocpgwdeployer.go
  pkg/rhos/securitygroups.go
Labels: automated-backport

#312 Allow dependabot upgrades on release-0.13
  .github/dependabot.yml
Labels: dependencies
