Repository submariner-io/cloud-prepare, pull requests merged in 2022-03, with the labels that each got.

#214 Add packagedoc-lint PR linting, fix errors
  .github/workflows/linting.yml
  pkg/api/api.go
  pkg/api/logging_reporter.go
  pkg/aws/aws.go
  pkg/aws/ec2helpers.go
  pkg/aws/errors.go
  pkg/aws/gw-machineset.go
  pkg/aws/ocpgwdeployer.go
  pkg/aws/securitygroups.go
  pkg/aws/subnets.go
  pkg/aws/validations.go
  pkg/aws/vpcs.go
  pkg/gcp/cloud_info.go
  pkg/gcp/firewall_rules.go
  pkg/gcp/gcp.go
  pkg/gcp/gcp_cloud_test.go
  pkg/gcp/gcp_suite_test.go
  pkg/gcp/gw-machineset.go
  pkg/gcp/ocpgwdeployer.go
  pkg/rhos/gw-machineset.go
  pkg/rhos/ocpgwdeployer.go
  pkg/rhos/rhos.go
  pkg/rhos/securitygroups.go
Labels: backport, automation

#215 Add packagedoc-lint linting, fix errors
  .github/workflows/linting.yml
  pkg/api/api.go
  pkg/api/logging_reporter.go
  pkg/aws/aws.go
  pkg/aws/ec2helpers.go
  pkg/aws/errors.go
  pkg/aws/gw-machineset.go
  pkg/aws/ocpgwdeployer.go
  pkg/aws/securitygroups.go
  pkg/aws/subnets.go
  pkg/aws/validations.go
  pkg/aws/vpcs.go
  pkg/gcp/cloud_info.go
  pkg/gcp/firewall_rules.go
  pkg/gcp/gcp.go
  pkg/gcp/gcp_cloud_test.go
  pkg/gcp/gcp_suite_test.go
  pkg/gcp/gw-machineset.go
  pkg/gcp/ocpgwdeployer.go
  pkg/rhos/gw-machineset.go
  pkg/rhos/ocpgwdeployer.go
  pkg/rhos/rhos.go
  pkg/rhos/securitygroups.go
Labels: automation

#224 Update actions/upload-artifact from 2.2.4 to 3.0.0
  .github/workflows/unit.yml
Labels: automation

#226 Only ignore Dockerfile.* in the root directory
  .gitignore
Labels: ready-to-test
