Repository submariner-io/cloud-prepare, pull requests merged in 2022-12, with the labels that each got.

#493 Cause dependabot to give all go updates at once
  .github/dependabot.yml
Labels: automation

#505 Bump to Go 1.19
  go.mod
  go.sum
Labels: maintenance

#506 Use k8s.io/utils/pointer instead of go-autorest/to
  go.mod
  go.sum
  pkg/azure/cloud_info.go
  pkg/azure/ocpgwdeployer.go
Labels: dependencies, backport, maintenance

#530 Automated backport of #506: Use k8s.io/utils/pointer instead of go-autorest/to
  go.mod
  go.sum
  pkg/azure/cloud_info.go
  pkg/azure/ocpgwdeployer.go
Labels: automated-backport
