Repository submariner-io/cloud-prepare, pull requests merged in 2023-02, with the labels that each got.

#508 Fix issues in cloud prepare for Azure and RHOS
  pkg/azure/ocpgwdeployer.go
  pkg/azure/ocpgwdeployer_test.go
  pkg/gcp/ocpgwdeployer_test.go
  pkg/ocp/fake/machineset.go
  pkg/ocp/machinesets.go
  pkg/ocp/machinesets_test.go
  pkg/rhos/ocpgwdeployer.go
Labels: ready-to-test, backport-needed

#582 Automated backport of #508: Fix issues in cloud prepare for Azure and RHOS
  pkg/azure/ocpgwdeployer.go
  pkg/azure/ocpgwdeployer_test.go
  pkg/gcp/ocpgwdeployer_test.go
  pkg/ocp/fake/machineset.go
  pkg/ocp/machinesets.go
  pkg/ocp/machinesets_test.go
  pkg/rhos/ocpgwdeployer.go
Labels: automated-backport

#581 Use a single gomod / dependabot configuration
  .github/dependabot.yml
Labels: dependencies, maintenance

#594 For Azure cloud prepare get the image from existing Machineset
  pkg/azure/gw-machineset.go
  pkg/azure/ocpgwdeployer.go
  pkg/ocp/machinesets.go
Labels: priority:high, backport

#595 Avoid double MachineSet retrieval
  pkg/azure/ocpgwdeployer.go
  pkg/gcp/ocpgwdeployer.go
  pkg/gcp/ocpgwdeployer_test.go
  pkg/ocp/fake/machineset.go
  pkg/ocp/machinesets.go
  pkg/ocp/machinesets_test.go
  pkg/rhos/ocpgwdeployer.go
Labels: maintenance

#597 Automated backport of #383: Dedicated g/w deletiiong using machineset list
  pkg/ocp/fake/machineset.go
  pkg/ocp/machinesets.go
  pkg/ocp/machinesets_test.go
  pkg/rhos/ocpgwdeployer.go
Labels: ready-to-test, automated-backport

#600 Automated backport of #508: Fix issues in cloud prepare for Azure and RHOS
  pkg/azure/ocpgwdeployer.go
  pkg/azure/ocpgwdeployer_test.go
  pkg/gcp/ocpgwdeployer_test.go
  pkg/ocp/fake/machineset.go
  pkg/ocp/machinesets.go
  pkg/ocp/machinesets_test.go
  pkg/rhos/ocpgwdeployer.go
Labels: ready-to-test, automated-backport
